import {
  Achievement,
  Course,
  ImpactStat,
  Learner,
  LeaderboardEntry,
  MentorSession,
} from "@/types";

export const currentLearner: Learner = {
  id: "u1",
  name: "Amara",
  initials: "AM",
  streakDays: 12,
  weeklyGoalMinutes: 300,
  weeklyMinutesCompleted: 214,
};

export const courses: Course[] = [
  // ── Data & Analytics ────────────────────────────────────────────────────
  {
    id: "c1",
    title: "Foundations of Data Literacy",
    category: "Data & Analytics",
    mentor: "Wale Adebayo",
    totalLessons: 24,
    completedLessons: 16,
    durationMinutes: 480,
    coverTone: "indigo",
    free: true,
  },
  {
    id: "c5",
    title: "SQL for Beginners",
    category: "Data & Analytics",
    mentor: "Wale Adebayo",
    totalLessons: 20,
    completedLessons: 0,
    durationMinutes: 360,
    coverTone: "indigo",
    free: true,
  },
  {
    id: "c9",
    title: "Data Visualization with Charts",
    category: "Data & Analytics",
    mentor: "Wale Adebayo",
    totalLessons: 16,
    completedLessons: 8,
    durationMinutes: 300,
    coverTone: "teal",
    free: true,
  },
  {
    id: "c13",
    title: "Python for Data Analysis",
    category: "Data & Analytics",
    mentor: "Wale Adebayo",
    totalLessons: 30,
    completedLessons: 0,
    durationMinutes: 540,
    coverTone: "indigo",
    free: true,
  },
  {
    id: "c14",
    title: "Excel Mastery for Analysts",
    category: "Data & Analytics",
    mentor: "Wale Adebayo",
    totalLessons: 22,
    completedLessons: 22,
    durationMinutes: 396,
    coverTone: "gold",
    free: true,
  },
  {
    id: "c15",
    title: "Statistical Thinking for Non-Mathematicians",
    category: "Data & Analytics",
    mentor: "Wale Adebayo",
    totalLessons: 18,
    completedLessons: 6,
    durationMinutes: 324,
    coverTone: "teal",
    free: true,
  },

  // ── Communication ───────────────────────────────────────────────────────
  {
    id: "c2",
    title: "Spoken English for Interviews",
    category: "Communication",
    mentor: "Grace Nwosu",
    totalLessons: 18,
    completedLessons: 5,
    durationMinutes: 270,
    coverTone: "teal",
    free: true,
  },
  {
    id: "c6",
    title: "Business Writing Essentials",
    category: "Communication",
    mentor: "Grace Nwosu",
    totalLessons: 14,
    completedLessons: 14,
    durationMinutes: 210,
    coverTone: "teal",
    free: true,
  },
  {
    id: "c10",
    title: "Public Speaking Confidence",
    category: "Communication",
    mentor: "Grace Nwosu",
    totalLessons: 12,
    completedLessons: 3,
    durationMinutes: 180,
    coverTone: "rose",
    free: true,
  },
  {
    id: "c16",
    title: "Email & Workplace Communication",
    category: "Communication",
    mentor: "Grace Nwosu",
    totalLessons: 10,
    completedLessons: 0,
    durationMinutes: 150,
    coverTone: "indigo",
    free: true,
  },
  {
    id: "c17",
    title: "Negotiation Skills for the Workplace",
    category: "Communication",
    mentor: "Grace Nwosu",
    totalLessons: 16,
    completedLessons: 9,
    durationMinutes: 240,
    coverTone: "gold",
    free: true,
  },
  {
    id: "c18",
    title: "Active Listening & Empathetic Communication",
    category: "Communication",
    mentor: "Grace Nwosu",
    totalLessons: 8,
    completedLessons: 0,
    durationMinutes: 120,
    coverTone: "rose",
    free: true,
  },

  // ── Software ────────────────────────────────────────────────────────────
  {
    id: "c3",
    title: "Intro to Web Development",
    category: "Software",
    mentor: "Tunde Bakare",
    totalLessons: 32,
    completedLessons: 32,
    durationMinutes: 640,
    coverTone: "gold",
    free: true,
  },
  {
    id: "c7",
    title: "React Fundamentals",
    category: "Software",
    mentor: "Tunde Bakare",
    totalLessons: 28,
    completedLessons: 10,
    durationMinutes: 560,
    coverTone: "indigo",
    free: true,
  },
  {
    id: "c11",
    title: "Git & Version Control",
    category: "Software",
    mentor: "Tunde Bakare",
    totalLessons: 10,
    completedLessons: 10,
    durationMinutes: 140,
    coverTone: "rose",
    free: true,
  },
  {
    id: "c19",
    title: "JavaScript: Zero to Functional",
    category: "Software",
    mentor: "Tunde Bakare",
    totalLessons: 36,
    completedLessons: 0,
    durationMinutes: 720,
    coverTone: "gold",
    free: true,
  },
  {
    id: "c20",
    title: "APIs & the Modern Web",
    category: "Software",
    mentor: "Tunde Bakare",
    totalLessons: 14,
    completedLessons: 5,
    durationMinutes: 252,
    coverTone: "teal",
    free: true,
  },
  {
    id: "c21",
    title: "Command Line Essentials",
    category: "Software",
    mentor: "Tunde Bakare",
    totalLessons: 8,
    completedLessons: 8,
    durationMinutes: 96,
    coverTone: "indigo",
    free: true,
  },

  // ── Life Skills ─────────────────────────────────────────────────────────
  {
    id: "c4",
    title: "Personal Finance Basics",
    category: "Life Skills",
    mentor: "Ifeoma Chukwu",
    totalLessons: 12,
    completedLessons: 2,
    durationMinutes: 150,
    coverTone: "rose",
    free: true,
  },
  {
    id: "c8",
    title: "Budgeting on a Variable Income",
    category: "Life Skills",
    mentor: "Ifeoma Chukwu",
    totalLessons: 10,
    completedLessons: 0,
    durationMinutes: 120,
    coverTone: "gold",
    free: true,
  },
  {
    id: "c12",
    title: "Career Planning & Goal Setting",
    category: "Life Skills",
    mentor: "Ifeoma Chukwu",
    totalLessons: 8,
    completedLessons: 1,
    durationMinutes: 100,
    coverTone: "teal",
    free: true,
  },
  {
    id: "c22",
    title: "Time Management for Busy Learners",
    category: "Life Skills",
    mentor: "Ifeoma Chukwu",
    totalLessons: 10,
    completedLessons: 10,
    durationMinutes: 130,
    coverTone: "rose",
    free: true,
  },
  {
    id: "c23",
    title: "Avoiding Debt Traps",
    category: "Life Skills",
    mentor: "Ifeoma Chukwu",
    totalLessons: 6,
    completedLessons: 0,
    durationMinutes: 75,
    coverTone: "indigo",
    free: true,
  },
  {
    id: "c24",
    title: "Building Healthy Habits That Stick",
    category: "Life Skills",
    mentor: "Ifeoma Chukwu",
    totalLessons: 9,
    completedLessons: 4,
    durationMinutes: 108,
    coverTone: "gold",
    free: true,
  },

  // ── Design ──────────────────────────────────────────────────────────────
  {
    id: "c25",
    title: "UI Design Principles from Scratch",
    category: "Design",
    mentor: "Simi Adeyemi",
    totalLessons: 24,
    completedLessons: 12,
    durationMinutes: 432,
    coverTone: "rose",
    free: true,
  },
  {
    id: "c26",
    title: "Figma for Absolute Beginners",
    category: "Design",
    mentor: "Simi Adeyemi",
    totalLessons: 18,
    completedLessons: 0,
    durationMinutes: 270,
    coverTone: "teal",
    free: true,
  },
  {
    id: "c27",
    title: "Colour Theory & Typography in Practice",
    category: "Design",
    mentor: "Simi Adeyemi",
    totalLessons: 12,
    completedLessons: 12,
    durationMinutes: 180,
    coverTone: "gold",
    free: true,
  },
  {
    id: "c28",
    title: "Portfolio Design for Creatives",
    category: "Design",
    mentor: "Simi Adeyemi",
    totalLessons: 10,
    completedLessons: 3,
    durationMinutes: 150,
    coverTone: "indigo",
    free: true,
  },

  // ── Business ────────────────────────────────────────────────────────────
  {
    id: "c29",
    title: "Starting a Small Business in Africa",
    category: "Business",
    mentor: "Emeka Osei",
    totalLessons: 20,
    completedLessons: 7,
    durationMinutes: 360,
    coverTone: "gold",
    free: true,
  },
  {
    id: "c30",
    title: "Digital Marketing Fundamentals",
    category: "Business",
    mentor: "Emeka Osei",
    totalLessons: 16,
    completedLessons: 0,
    durationMinutes: 240,
    coverTone: "teal",
    free: true,
  },
  {
    id: "c31",
    title: "Freelancing: Getting Your First Client",
    category: "Business",
    mentor: "Emeka Osei",
    totalLessons: 12,
    completedLessons: 12,
    durationMinutes: 180,
    coverTone: "rose",
    free: true,
  },
  {
    id: "c32",
    title: "Business Basics: From Idea to Revenue",
    category: "Business",
    mentor: "Emeka Osei",
    totalLessons: 22,
    completedLessons: 4,
    durationMinutes: 330,
    coverTone: "indigo",
    free: true,
  },

  // ── Health & Wellness ───────────────────────────────────────────────────
  {
    id: "c33",
    title: "Mental Health Awareness for Students",
    category: "Health & Wellness",
    mentor: "Dr. Aisha Bello",
    totalLessons: 14,
    completedLessons: 6,
    durationMinutes: 210,
    coverTone: "teal",
    free: true,
  },
  {
    id: "c34",
    title: "Stress Management & Resilience",
    category: "Health & Wellness",
    mentor: "Dr. Aisha Bello",
    totalLessons: 10,
    completedLessons: 0,
    durationMinutes: 150,
    coverTone: "rose",
    free: true,
  },
  {
    id: "c35",
    title: "Nutrition Basics for Everyday Life",
    category: "Health & Wellness",
    mentor: "Dr. Aisha Bello",
    totalLessons: 12,
    completedLessons: 12,
    durationMinutes: 144,
    coverTone: "gold",
    free: true,
  },

  // ── Languages ───────────────────────────────────────────────────────────
  {
    id: "c36",
    title: "French for Beginners",
    category: "Languages",
    mentor: "Grace Nwosu",
    totalLessons: 30,
    completedLessons: 0,
    durationMinutes: 450,
    coverTone: "indigo",
    free: true,
  },
  {
    id: "c37",
    title: "Yoruba Language & Culture",
    category: "Languages",
    mentor: "Grace Nwosu",
    totalLessons: 20,
    completedLessons: 11,
    durationMinutes: 300,
    coverTone: "gold",
    free: true,
  },
  {
    id: "c38",
    title: "Professional Swahili for Business",
    category: "Languages",
    mentor: "Grace Nwosu",
    totalLessons: 18,
    completedLessons: 0,
    durationMinutes: 270,
    coverTone: "teal",
    free: true,
  },
];

export const achievements: Achievement[] = [
  { id: "a1", title: "30-Day Streak", tier: "gold", earnedOn: "Jun 2026" },
  { id: "a2", title: "First Course Complete", tier: "gold", earnedOn: "May 2026" },
  { id: "a3", title: "Community Mentor", tier: "silver", earnedOn: "May 2026" },
  { id: "a4", title: "Early Riser", tier: "bronze", earnedOn: "Apr 2026" },
];

export const leaderboard: LeaderboardEntry[] = [
  { id: "l1", name: "Chidera O.", initials: "CO", points: 2840, rank: 1 },
  { id: "l2", name: "Amara", initials: "AM", points: 2615, rank: 2, isCurrentUser: true },
  { id: "l3", name: "Femi A.", initials: "FA", points: 2400, rank: 3 },
  { id: "l4", name: "Ngozi E.", initials: "NE", points: 2180, rank: 4 },
];

export const impactStats: ImpactStat[] = [
  { id: "i1", label: "Learners funded this month", value: 742, goal: 1000, unit: "learners" },
  { id: "i2", label: "Scholarship hours unlocked", value: 5230, goal: 8000, unit: "hours" },
];

export const upcomingSession: MentorSession = {
  id: "s1",
  title: "Live Q&A: Breaking into Data Roles",
  mentor: "Wale Adebayo",
  date: "Fri, Jul 3",
  time: "6:00 PM WAT",
};

export interface Instructor {
  id: string;
  slug: string;
  name: string;
  initials: string;
  title: string;
  bio: string;
  longBio: string;
  expertise: string[];
  coursesTaught: number;
  learnersReached: number;
}

export const instructors: Instructor[] = [
  {
    id: "in1",
    slug: "wale-adebayo",
    name: "Wale Adebayo",
    initials: "WA",
    title: "Data & Analytics Mentor",
    bio: "Data analyst turned educator, focused on making data literacy accessible to first-generation tech learners.",
    longBio:
      "Wale spent six years as a data analyst before moving into education full-time. He believes the biggest barrier to data careers isn't talent, it's access to plain-language teaching — so that's what he builds. Outside MindGrid, he runs a monthly data-storytelling meetup.",
    expertise: ["Data Literacy", "SQL", "Python", "Data Visualization"],
    coursesTaught: 6,
    learnersReached: 1240,
  },
  {
    id: "in2",
    slug: "grace-nwosu",
    name: "Grace Nwosu",
    initials: "GN",
    title: "Communication & Languages Coach",
    bio: "Communication coach helping learners speak with confidence in interviews, pitches, and the workplace — also teaches African languages.",
    longBio:
      "Grace has coached over a thousand job-seekers on interview communication. Her MindGrid courses focus on practical, low-pressure practice — she's especially known for helping non-native English speakers build interview confidence without losing their voice. She recently added language courses after noticing learners wanted to reconnect with their heritage.",
    expertise: ["Public Speaking", "Interview Prep", "Business English", "Languages"],
    coursesTaught: 9,
    learnersReached: 980,
  },
  {
    id: "in3",
    slug: "tunde-bakare",
    name: "Tunde Bakare",
    initials: "TB",
    title: "Software Engineering Mentor",
    bio: "Full-stack engineer teaching practical, job-ready web development from first principles.",
    longBio:
      "Tunde has shipped production software for a decade, most recently at a fintech startup. He teaches the way he wishes he'd been taught — project-first, with real deployment from lesson one — and mentors several MindGrid learners into their first junior developer roles each year.",
    expertise: ["JavaScript", "React", "Web Fundamentals", "APIs"],
    coursesTaught: 6,
    learnersReached: 2150,
  },
  {
    id: "in4",
    slug: "ifeoma-chukwu",
    name: "Ifeoma Chukwu",
    initials: "IC",
    title: "Life Skills Mentor",
    bio: "Financial literacy educator making personal finance approachable for first-time earners.",
    longBio:
      "Ifeoma spent years in retail banking before realizing most of her clients had never been taught the basics anyone needs to manage money well. Her MindGrid courses are built for people earning their first income — budgeting, saving, and avoiding common debt traps, explained without jargon.",
    expertise: ["Budgeting", "Saving", "Financial Planning", "Habits"],
    coursesTaught: 6,
    learnersReached: 860,
  },
  {
    id: "in5",
    slug: "simi-adeyemi",
    name: "Simi Adeyemi",
    initials: "SA",
    title: "UI/UX Design Mentor",
    bio: "Product designer with 8 years of industry experience, teaching design thinking and tools from the ground up.",
    longBio:
      "Simi has designed products used by millions across fintech, healthtech, and e-commerce. She joined MindGrid because she saw brilliant aspiring designers blocked by tool costs and gatekeeping — her courses are built to remove both barriers, starting from zero assumed knowledge.",
    expertise: ["UI Design", "Figma", "Typography", "Portfolio Building"],
    coursesTaught: 4,
    learnersReached: 730,
  },
  {
    id: "in6",
    slug: "emeka-osei",
    name: "Emeka Osei",
    initials: "EO",
    title: "Business & Entrepreneurship Mentor",
    bio: "Serial entrepreneur and business strategist helping emerging founders navigate starting and growing a business in Africa.",
    longBio:
      "Emeka has started four businesses across Ghana and Nigeria, one of which he scaled and exited. He now teaches entrepreneurship because he's tired of watching talented people fail for lack of practical business knowledge that no one teaches in school. His courses skip the theory and go straight to what works.",
    expertise: ["Entrepreneurship", "Digital Marketing", "Freelancing", "Business Strategy"],
    coursesTaught: 4,
    learnersReached: 615,
  },
  {
    id: "in7",
    slug: "dr-aisha-bello",
    name: "Dr. Aisha Bello",
    initials: "AB",
    title: "Health & Wellness Educator",
    bio: "Clinical psychologist bringing evidence-based mental health and wellness education to everyday learners.",
    longBio:
      "Dr. Aisha Bello is a clinical psychologist who spent a decade in clinical practice before pivoting to education. She found that most of her patients had never had access to basic mental health literacy, and believes early education prevents much of what she used to treat. Her MindGrid courses are grounded in real clinical evidence, not wellness buzzwords.",
    expertise: ["Mental Health", "Stress Management", "Nutrition", "Resilience"],
    coursesTaught: 3,
    learnersReached: 490,
  },
];
